spring:
  profiles:
    active: test

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mybatisdemo
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  data:
    mongodb:
      host: localhost
      port: 27017
      #username:
      #password:
      database: test
#      #authenticationDatabase: # Authentication database name.
#      #fieldNamingStrategy: # Fully qualified name of the FieldNamingStrategy to use.
#      repositories:
#        enabled:true # Enable Mongo repositories.
#      #uri:mongodb://localhost/test # Mongo database URI. When set, host and port are ignored.

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.0.121 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #password:  # Redis服务器连接密码（默认为空）
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接

mybatis:
    # 配置类型别名
    typeAliasesPackage: com.stt.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/**/*.xml
    # 加载全局的配置文件
    configLocation: classpath:config/mybatis-config.xml


